/**
 * Templates predefinidos para documentos médicos
 * Basados en requisitos del Conselho Federal de Medicina (CFM) de Brasil
 * y normativas de documentación médica
 */

// Función auxiliar para generar IDs únicos
const generateId = () => `el_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;

export const getPredefinedTemplates = () => [
  // ========== HEADERS PARA RECEITAS MÉDICAS (CFM) ==========
  {
    id: 'header_prescription_cfm',
    name: 'Receita - Padrão CFM',
    description: 'Header conforme CFM com dados obrigatórios',
    section: 'header',
    documentType: 'prescription',
    pageSize: 'A4',
    orientation: 'portrait',
    icon: 'bi bi-capsule',
    elements: [
      {
        id: generateId(),
        type: 'logo',
        x: 50,
        y: 20,
        width: 70,
        height: 70,
        src: '{{commerceLogo}}',
      },
      {
        id: generateId(),
        type: 'text',
        x: 140,
        y: 25,
        width: 405,
        height: 20,
        text: '{{commerceName}}',
        fontSize: 14,
        fontFamily: 'Arial',
        color: '#000000',
        align: 'left',
        bold: true,
      },
      {
        id: generateId(),
        type: 'text',
        x: 140,
        y: 45,
        width: 405,
        height: 16,
        text: 'Dr(a). {{doctorName}}',
        fontSize: 12,
        fontFamily: 'Arial',
        color: '#1a5490',
        align: 'left',
        bold: true,
      },
      {
        id: generateId(),
        type: 'text',
        x: 140,
        y: 62,
        width: 405,
        height: 14,
        text: 'CRM: {{doctorLicense}} | {{doctorSpecialty}}',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#000000',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'text',
        x: 140,
        y: 77,
        width: 405,
        height: 14,
        text: 'Endereço: {{commerceAddress}}',
        fontSize: 9,
        fontFamily: 'Arial',
        color: '#495057',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'text',
        x: 140,
        y: 92,
        width: 405,
        height: 14,
        text: 'Tel: {{commercePhone}} | Email: {{commerceEmail}}',
        fontSize: 9,
        fontFamily: 'Arial',
        color: '#495057',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'line',
        x: 50,
        y: 115,
        width: 495,
        height: 2,
        strokeWidth: 2,
        strokeColor: '#000000',
      },
    ],
  },
  {
    id: 'header_prescription_simple',
    name: 'Receita - Simples',
    description: 'Header básico com informações essenciais',
    section: 'header',
    documentType: 'prescription',
    pageSize: 'A4',
    orientation: 'portrait',
    icon: 'bi bi-file-medical',
    elements: [
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 25,
        width: 495,
        height: 24,
        text: 'Dr(a). {{doctorName}}',
        fontSize: 16,
        fontFamily: 'Arial',
        color: '#1a5490',
        align: 'center',
        bold: true,
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 50,
        width: 495,
        height: 18,
        text: '{{doctorSpecialty}}',
        fontSize: 12,
        fontFamily: 'Arial',
        color: '#495057',
        align: 'center',
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 70,
        width: 495,
        height: 16,
        text: 'CRM: {{doctorLicense}}',
        fontSize: 11,
        fontFamily: 'Arial',
        color: '#000000',
        align: 'center',
        bold: true,
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 88,
        width: 495,
        height: 14,
        text: '{{commerceAddress}} | Tel: {{commercePhone}}',
        fontSize: 9,
        fontFamily: 'Arial',
        color: '#6c757d',
        align: 'center',
      },
      {
        id: generateId(),
        type: 'line',
        x: 50,
        y: 110,
        width: 495,
        height: 1,
        strokeWidth: 1,
        strokeColor: '#dee2e6',
      },
    ],
  },

  // ========== HEADERS PARA PEDIDOS DE EXAME ==========
  {
    id: 'header_exam_order_cfm',
    name: 'Pedido de Exame - CFM',
    description: 'Header para solicitação de exames',
    section: 'header',
    documentType: 'exam_order',
    pageSize: 'A4',
    orientation: 'portrait',
    icon: 'bi bi-clipboard2-pulse',
    elements: [
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 20,
        width: 495,
        height: 28,
        text: 'SOLICITAÇÃO DE EXAMES',
        fontSize: 18,
        fontFamily: 'Arial',
        color: '#1a5490',
        align: 'center',
        bold: true,
      },
      {
        id: generateId(),
        type: 'line',
        x: 50,
        y: 52,
        width: 495,
        height: 2,
        strokeWidth: 2,
        strokeColor: '#1a5490',
      },
      {
        id: generateId(),
        type: 'logo',
        x: 50,
        y: 62,
        width: 60,
        height: 60,
        src: '{{commerceLogo}}',
      },
      {
        id: generateId(),
        type: 'text',
        x: 125,
        y: 65,
        width: 420,
        height: 18,
        text: '{{commerceName}}',
        fontSize: 12,
        fontFamily: 'Arial',
        color: '#000000',
        align: 'left',
        bold: true,
      },
      {
        id: generateId(),
        type: 'text',
        x: 125,
        y: 83,
        width: 420,
        height: 16,
        text: 'Dr(a). {{doctorName}} - CRM: {{doctorLicense}}',
        fontSize: 11,
        fontFamily: 'Arial',
        color: '#1a5490',
        align: 'left',
        bold: true,
      },
      {
        id: generateId(),
        type: 'text',
        x: 125,
        y: 100,
        width: 420,
        height: 14,
        text: '{{doctorSpecialty}}',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#495057',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'text',
        x: 125,
        y: 115,
        width: 420,
        height: 12,
        text: 'End: {{commerceAddress}} | Tel: {{commercePhone}}',
        fontSize: 9,
        fontFamily: 'Arial',
        color: '#6c757d',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'line',
        x: 50,
        y: 135,
        width: 495,
        height: 1,
        strokeWidth: 1,
        strokeColor: '#dee2e6',
      },
    ],
  },

  // ========== HEADERS PARA GUIA DE REFERÊNCIA/ENCAMINHAMENTO ==========
  {
    id: 'header_reference_cfm',
    name: 'Encaminhamento - CFM',
    description: 'Header para guia de encaminhamento médico',
    section: 'header',
    documentType: 'reference',
    pageSize: 'A4',
    orientation: 'portrait',
    icon: 'bi bi-arrow-right-square',
    elements: [
      {
        id: generateId(),
        type: 'logo',
        x: 50,
        y: 20,
        width: 75,
        height: 75,
        src: '{{commerceLogo}}',
      },
      {
        id: generateId(),
        type: 'text',
        x: 140,
        y: 25,
        width: 405,
        height: 22,
        text: '{{commerceName}}',
        fontSize: 14,
        fontFamily: 'Arial',
        color: '#1a5490',
        align: 'left',
        bold: true,
      },
      {
        id: generateId(),
        type: 'text',
        x: 140,
        y: 48,
        width: 405,
        height: 18,
        text: 'Dr(a). {{doctorName}}',
        fontSize: 12,
        fontFamily: 'Arial',
        color: '#000000',
        align: 'left',
        bold: true,
      },
      {
        id: generateId(),
        type: 'text',
        x: 140,
        y: 67,
        width: 405,
        height: 16,
        text: 'CRM: {{doctorLicense}} | {{doctorSpecialty}}',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#000000',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'text',
        x: 140,
        y: 84,
        width: 405,
        height: 14,
        text: '{{commerceAddress}} | Tel: {{commercePhone}}',
        fontSize: 9,
        fontFamily: 'Arial',
        color: '#6c757d',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'line',
        x: 50,
        y: 105,
        width: 495,
        height: 2,
        strokeWidth: 2,
        strokeColor: '#1a5490',
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 115,
        width: 495,
        height: 24,
        text: 'GUIA DE ENCAMINHAMENTO / REFERÊNCIA',
        fontSize: 14,
        fontFamily: 'Arial',
        color: '#1a5490',
        align: 'center',
        bold: true,
      },
    ],
  },

  // ========== FOOTERS PARA RECEITAS (CFM - Requisitos obrigatórios) ==========
  {
    id: 'footer_prescription_cfm',
    name: 'Receita - Assinatura CFM',
    description: 'Footer com assinatura e data conforme CFM',
    section: 'footer',
    documentType: 'prescription',
    pageSize: 'A4',
    orientation: 'portrait',
    icon: 'bi bi-pen',
    elements: [
      {
        id: generateId(),
        type: 'line',
        x: 50,
        y: 715,
        width: 495,
        height: 1,
        strokeWidth: 1,
        strokeColor: '#dee2e6',
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 725,
        width: 200,
        height: 14,
        text: 'Data de emissão:',
        fontSize: 9,
        fontFamily: 'Arial',
        color: '#495057',
        align: 'left',
        bold: true,
      },
      {
        id: generateId(),
        type: 'text',
        x: 150,
        y: 725,
        width: 150,
        height: 14,
        text: '{{prescriptionDate}}',
        fontSize: 9,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'text',
        x: 345,
        y: 725,
        width: 200,
        height: 14,
        text: 'Validade: 30 dias',
        fontSize: 9,
        fontFamily: 'Arial',
        color: '#495057',
        align: 'right',
      },
      {
        id: generateId(),
        type: 'signature',
        x: 80,
        y: 745,
        width: 130,
        height: 50,
        src: '{{doctorSignature}}',
      },
      {
        id: generateId(),
        type: 'line',
        x: 70,
        y: 800,
        width: 150,
        height: 1,
        strokeWidth: 1,
        strokeColor: '#000000',
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 805,
        width: 190,
        height: 14,
        text: 'Dr(a). {{doctorName}}',
        fontSize: 10,
        fontFamily: 'Lucida Handwriting',
        color: '#000000',
        align: 'center',
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 820,
        width: 190,
        height: 12,
        text: 'CRM: {{doctorLicense}}',
        fontSize: 9,
        fontFamily: 'Arial',
        color: '#000000',
        align: 'center',
        bold: true,
      },
      {
        id: generateId(),
        type: 'qrcode',
        x: 380,
        y: 745,
        width: 70,
        height: 70,
        data: '{{verificationUrl}}',
      },
      {
        id: generateId(),
        type: 'text',
        x: 350,
        y: 820,
        width: 130,
        height: 10,
        text: 'Verificar autenticidade',
        fontSize: 7,
        fontFamily: 'Arial',
        color: '#6c757d',
        align: 'center',
      },
    ],
  },
  {
    id: 'footer_prescription_digital',
    name: 'Receita - Digital',
    description: 'Footer com código de verificação digital',
    section: 'footer',
    documentType: 'prescription',
    pageSize: 'A4',
    orientation: 'portrait',
    icon: 'bi bi-qr-code',
    elements: [
      {
        id: generateId(),
        type: 'line',
        x: 50,
        y: 720,
        width: 495,
        height: 2,
        strokeWidth: 2,
        strokeColor: '#000000',
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 730,
        width: 295,
        height: 14,
        text: 'Local e data: {{commerceCity}}, {{prescriptionDate}}',
        fontSize: 9,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'signature',
        x: 70,
        y: 750,
        width: 140,
        height: 45,
        src: '{{doctorSignature}}',
      },
      {
        id: generateId(),
        type: 'line',
        x: 60,
        y: 800,
        width: 160,
        height: 1,
        strokeWidth: 1,
        strokeColor: '#000000',
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 805,
        width: 180,
        height: 13,
        text: 'Dr(a). {{doctorName}}',
        fontSize: 10,
        fontFamily: 'Brush Script MT',
        color: '#000000',
        align: 'center',
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 820,
        width: 180,
        height: 11,
        text: 'CRM: {{doctorLicense}}',
        fontSize: 9,
        fontFamily: 'Arial',
        color: '#000000',
        align: 'center',
        bold: true,
      },
      {
        id: generateId(),
        type: 'qrcode',
        x: 385,
        y: 745,
        width: 75,
        height: 75,
        data: '{{verificationUrl}}',
      },
      {
        id: generateId(),
        type: 'text',
        x: 350,
        y: 825,
        width: 145,
        height: 10,
        text: 'Doc. ID: {{documentId}}',
        fontSize: 7,
        fontFamily: 'Arial',
        color: '#adb5bd',
        align: 'center',
      },
    ],
  },

  // ========== FOOTERS PARA PEDIDOS DE EXAME ==========
  {
    id: 'footer_exam_order_cfm',
    name: 'Exame - Completo CFM',
    description: 'Footer com instruções e assinatura',
    section: 'footer',
    documentType: 'exam_order',
    pageSize: 'A4',
    orientation: 'portrait',
    icon: 'bi bi-clipboard-check',
    elements: [
      {
        id: generateId(),
        type: 'line',
        x: 50,
        y: 700,
        width: 495,
        height: 1,
        strokeWidth: 1,
        strokeColor: '#dee2e6',
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 710,
        width: 495,
        height: 16,
        text: 'OBSERVAÇÕES:',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#dc3545',
        align: 'left',
        bold: true,
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 728,
        width: 495,
        height: 12,
        text: '• Apresentar documento de identidade no laboratório',
        fontSize: 9,
        fontFamily: 'Arial',
        color: '#495057',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 742,
        width: 495,
        height: 12,
        text: '• Seguir as instruções de preparo especificadas',
        fontSize: 9,
        fontFamily: 'Arial',
        color: '#495057',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 756,
        width: 495,
        height: 12,
        text: '• Validade desta solicitação: 30 dias',
        fontSize: 9,
        fontFamily: 'Arial',
        color: '#495057',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 775,
        width: 200,
        height: 12,
        text: 'Data: {{currentDate}}',
        fontSize: 9,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'signature',
        x: 80,
        y: 790,
        width: 120,
        height: 40,
        src: '{{doctorSignature}}',
      },
      {
        id: generateId(),
        type: 'line',
        x: 70,
        y: 833,
        width: 140,
        height: 1,
        strokeWidth: 1,
        strokeColor: '#000000',
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 838,
        width: 180,
        height: 11,
        text: 'Dr(a). {{doctorName}}',
        fontSize: 9,
        fontFamily: 'Arial',
        color: '#000000',
        align: 'center',
        bold: true,
      },
      {
        id: generateId(),
        type: 'text',
        x: 345,
        y: 800,
        width: 200,
        height: 12,
        text: 'CRM: {{doctorLicense}}',
        fontSize: 9,
        fontFamily: 'Arial',
        color: '#000000',
        align: 'right',
        bold: true,
      },
      {
        id: generateId(),
        type: 'text',
        x: 345,
        y: 815,
        width: 200,
        height: 11,
        text: '{{doctorSpecialty}}',
        fontSize: 8,
        fontFamily: 'Arial',
        color: '#6c757d',
        align: 'right',
      },
    ],
  },

  // ========== FOOTERS PARA ENCAMINHAMENTO/REFERÊNCIA ==========
  {
    id: 'footer_reference_cfm',
    name: 'Encaminhamento - CFM',
    description: 'Footer para guia de referência',
    section: 'footer',
    documentType: 'reference',
    pageSize: 'A4',
    orientation: 'portrait',
    icon: 'bi bi-telephone',
    elements: [
      {
        id: generateId(),
        type: 'line',
        x: 50,
        y: 710,
        width: 495,
        height: 2,
        strokeWidth: 2,
        strokeColor: '#1a5490',
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 720,
        width: 495,
        height: 16,
        text: 'SOLICITAÇÃO DE CONTRARREFERÊNCIA',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#1a5490',
        align: 'left',
        bold: true,
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 738,
        width: 495,
        height: 12,
        text: 'Favor enviar relatório de evolução e conduta ao médico solicitante:',
        fontSize: 9,
        fontFamily: 'Arial',
        color: '#495057',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 752,
        width: 495,
        height: 12,
        text: 'Tel: {{commercePhone}} | Email: {{commerceEmail}}',
        fontSize: 9,
        fontFamily: 'Arial',
        color: '#495057',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 772,
        width: 200,
        height: 12,
        text: 'Data: {{currentDate}}',
        fontSize: 9,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'signature',
        x: 80,
        y: 790,
        width: 130,
        height: 45,
        src: '{{doctorSignature}}',
      },
      {
        id: generateId(),
        type: 'line',
        x: 70,
        y: 838,
        width: 150,
        height: 1,
        strokeWidth: 1,
        strokeColor: '#000000',
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 843,
        width: 190,
        height: 11,
        text: 'Dr(a). {{doctorName}}',
        fontSize: 9,
        fontFamily: 'Monotype Corsiva',
        color: '#000000',
        align: 'center',
      },
      {
        id: generateId(),
        type: 'text',
        x: 320,
        y: 795,
        width: 225,
        height: 12,
        text: 'CRM: {{doctorLicense}}',
        fontSize: 9,
        fontFamily: 'Arial',
        color: '#000000',
        align: 'right',
        bold: true,
      },
      {
        id: generateId(),
        type: 'text',
        x: 320,
        y: 810,
        width: 225,
        height: 11,
        text: '{{doctorSpecialty}}',
        fontSize: 8,
        fontFamily: 'Arial',
        color: '#6c757d',
        align: 'right',
      },
      {
        id: generateId(),
        type: 'text',
        x: 320,
        y: 825,
        width: 225,
        height: 10,
        text: 'Protocolo: {{documentId}}',
        fontSize: 8,
        fontFamily: 'Arial',
        color: '#adb5bd',
        align: 'right',
      },
    ],
  },

  // ========== CONTENT PARA RECEITAS (Elementos obrigatórios CFM) ==========
  {
    id: 'content_prescription_cfm_complete',
    name: 'Receita - Completa CFM',
    description: 'Formato completo conforme CFM',
    section: 'content',
    documentType: 'prescription',
    pageSize: 'A4',
    orientation: 'portrait',
    icon: 'bi bi-capsule',
    elements: [
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 145,
        width: 495,
        height: 28,
        text: 'RECEITA MÉDICA',
        fontSize: 18,
        fontFamily: 'Arial',
        color: '#1a5490',
        align: 'center',
        bold: true,
      },
      {
        id: generateId(),
        type: 'line',
        x: 50,
        y: 178,
        width: 495,
        height: 2,
        strokeWidth: 2,
        strokeColor: '#dee2e6',
      },
      // IDENTIFICAÇÃO DO PACIENTE (Obrigatório CFM)
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 195,
        width: 495,
        height: 18,
        text: 'IDENTIFICAÇÃO DO PACIENTE',
        fontSize: 11,
        fontFamily: 'Arial',
        color: '#1a5490',
        align: 'left',
        bold: true,
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 218,
        width: 245,
        height: 16,
        text: 'Nome: {{patientName}}',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'text',
        x: 300,
        y: 218,
        width: 245,
        height: 16,
        text: 'Idade: {{patientAge}} anos',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 236,
        width: 245,
        height: 16,
        text: 'CPF/RG: {{patientId}}',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'text',
        x: 300,
        y: 236,
        width: 245,
        height: 16,
        text: 'Data: {{prescriptionDate}}',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 254,
        width: 495,
        height: 16,
        text: 'Endereço: {{patientAddress}}',
        fontSize: 9,
        fontFamily: 'Arial',
        color: '#495057',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'line',
        x: 50,
        y: 275,
        width: 495,
        height: 1,
        strokeWidth: 1,
        strokeColor: '#dee2e6',
      },
      // PRESCRIÇÃO (Obrigatório CFM: nome do medicamento, posologia, via de administração, duração do tratamento)
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 290,
        width: 60,
        height: 30,
        text: 'Rp/',
        fontSize: 20,
        fontFamily: 'Times New Roman',
        color: '#000000',
        align: 'left',
        bold: true,
        italic: true,
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 325,
        width: 495,
        height: 320,
        text: '{{medications}}\n\nExemplo:\n1. Amoxicilina 500mg\n   Tomar 1 cápsula por via oral a cada 8 horas\n   Duração: 7 dias\n\n2. Dipirona 500mg\n   Tomar 1 comprimido por via oral a cada 6 horas se dor\n   Duração: conforme necessário (máx. 5 dias)',
        fontSize: 11,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'left',
        lineHeight: 1.7,
      },
      {
        id: generateId(),
        type: 'line',
        x: 50,
        y: 655,
        width: 495,
        height: 1,
        strokeWidth: 1,
        strokeColor: '#dee2e6',
      },
      // ORIENTAÇÕES ADICIONAIS
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 665,
        width: 495,
        height: 16,
        text: 'ORIENTAÇÕES:',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'left',
        bold: true,
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 683,
        width: 495,
        height: 35,
        text: '{{instructions}}',
        fontSize: 9,
        fontFamily: 'Arial',
        color: '#495057',
        align: 'left',
        lineHeight: 1.5,
      },
    ],
  },
  {
    id: 'content_prescription_standard',
    name: 'Receita - Padrão',
    description: 'Formato tradicional de receita',
    section: 'content',
    documentType: 'prescription',
    pageSize: 'A4',
    orientation: 'portrait',
    icon: 'bi bi-file-earmark-text',
    elements: [
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 140,
        width: 495,
        height: 26,
        text: 'PRESCRIÇÃO MÉDICA',
        fontSize: 16,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'left',
        bold: true,
      },
      {
        id: generateId(),
        type: 'line',
        x: 50,
        y: 170,
        width: 495,
        height: 1,
        strokeWidth: 1,
        strokeColor: '#000000',
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 185,
        width: 90,
        height: 16,
        text: 'Paciente:',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#000000',
        align: 'left',
        bold: true,
      },
      {
        id: generateId(),
        type: 'text',
        x: 140,
        y: 185,
        width: 405,
        height: 16,
        text: '{{patientName}}',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 204,
        width: 90,
        height: 16,
        text: 'CPF/RG:',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#000000',
        align: 'left',
        bold: true,
      },
      {
        id: generateId(),
        type: 'text',
        x: 140,
        y: 204,
        width: 180,
        height: 16,
        text: '{{patientId}}',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'text',
        x: 330,
        y: 204,
        width: 70,
        height: 16,
        text: 'Idade:',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#000000',
        align: 'left',
        bold: true,
      },
      {
        id: generateId(),
        type: 'text',
        x: 400,
        y: 204,
        width: 145,
        height: 16,
        text: '{{patientAge}} anos',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 223,
        width: 90,
        height: 16,
        text: 'Data:',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#000000',
        align: 'left',
        bold: true,
      },
      {
        id: generateId(),
        type: 'text',
        x: 140,
        y: 223,
        width: 405,
        height: 16,
        text: '{{prescriptionDate}}',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'line',
        x: 50,
        y: 248,
        width: 495,
        height: 2,
        strokeWidth: 2,
        strokeColor: '#dee2e6',
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 265,
        width: 50,
        height: 28,
        text: 'Rp/',
        fontSize: 18,
        fontFamily: 'Times New Roman',
        color: '#000000',
        align: 'left',
        bold: true,
        italic: true,
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 300,
        width: 495,
        height: 380,
        text: '{{medications}}',
        fontSize: 11,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'left',
        lineHeight: 1.8,
      },
    ],
  },

  // ========== CONTENT PARA PEDIDOS DE EXAME (CFM) ==========
  {
    id: 'content_exam_order_cfm',
    name: 'Exame - Padrão CFM',
    description: 'Solicitação conforme requisitos CFM',
    section: 'content',
    documentType: 'exam_order',
    pageSize: 'A4',
    orientation: 'portrait',
    icon: 'bi bi-clipboard2-pulse',
    elements: [
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 155,
        width: 495,
        height: 22,
        text: 'DADOS DO PACIENTE',
        fontSize: 12,
        fontFamily: 'Arial',
        color: '#1a5490',
        align: 'left',
        bold: true,
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 182,
        width: 245,
        height: 16,
        text: 'Nome: {{patientName}}',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'text',
        x: 300,
        y: 182,
        width: 245,
        height: 16,
        text: 'Data: {{currentDate}}',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 200,
        width: 245,
        height: 16,
        text: 'CPF/RG: {{patientId}}',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'text',
        x: 300,
        y: 200,
        width: 120,
        height: 16,
        text: 'Idade: {{patientAge}}',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'text',
        x: 425,
        y: 200,
        width: 120,
        height: 16,
        text: 'Sexo: {{patientGender}}',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 218,
        width: 495,
        height: 16,
        text: 'Convênio/Particular: {{patientInsurance}}',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'line',
        x: 50,
        y: 240,
        width: 495,
        height: 2,
        strokeWidth: 2,
        strokeColor: '#dee2e6',
      },
      // HIPÓTESE DIAGNÓSTICA (Obrigatório CFM para pedidos de exame)
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 252,
        width: 495,
        height: 20,
        text: 'HIPÓTESE DIAGNÓSTICA / CID-10',
        fontSize: 11,
        fontFamily: 'Arial',
        color: '#1a5490',
        align: 'left',
        bold: true,
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 275,
        width: 495,
        height: 45,
        text: '{{diagnosis}}',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'left',
        lineHeight: 1.6,
      },
      {
        id: generateId(),
        type: 'line',
        x: 50,
        y: 325,
        width: 495,
        height: 1,
        strokeWidth: 1,
        strokeColor: '#dee2e6',
      },
      // EXAMES SOLICITADOS (Obrigatório)
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 337,
        width: 495,
        height: 20,
        text: 'EXAMES SOLICITADOS',
        fontSize: 11,
        fontFamily: 'Arial',
        color: '#1a5490',
        align: 'left',
        bold: true,
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 360,
        width: 495,
        height: 200,
        text: '{{examsList}}\n\nExemplo:\n☐ Hemograma completo\n☐ Glicemia de jejum\n☐ Colesterol total e frações\n☐ TGO/TGP (Transaminases)\n☐ Ureia e creatinina',
        fontSize: 11,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'left',
        lineHeight: 2.0,
      },
      {
        id: generateId(),
        type: 'line',
        x: 50,
        y: 568,
        width: 495,
        height: 1,
        strokeWidth: 1,
        strokeColor: '#dee2e6',
      },
      // INSTRUÇÕES DE PREPARO (Importante)
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 580,
        width: 495,
        height: 18,
        text: 'INSTRUÇÕES DE PREPARO',
        fontSize: 11,
        fontFamily: 'Arial',
        color: '#dc3545',
        align: 'left',
        bold: true,
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 602,
        width: 495,
        height: 90,
        text: '{{preparationInstructions}}\n\nExemplo:\n• Jejum de 8 a 12 horas para glicemia e perfil lipídico\n• Trazer exames anteriores, se houver\n• Manter medicação habitual (exceto se orientado ao contrário)',
        fontSize: 9,
        fontFamily: 'Arial',
        color: '#495057',
        align: 'left',
        lineHeight: 1.6,
      },
    ],
  },

  // ========== HEADERS ADICIONALES VARIANTES ==========
  {
    id: 'header_prescription_modern',
    name: 'Receita - Moderna',
    description: 'Header com layout moderno e cores',
    section: 'header',
    documentType: 'prescription',
    pageSize: 'A4',
    orientation: 'portrait',
    icon: 'bi bi-capsule-pill',
    elements: [
      {
        id: generateId(),
        type: 'logo',
        x: 50,
        y: 20,
        width: 80,
        height: 80,
        src: '{{commerceLogo}}',
      },
      {
        id: generateId(),
        type: 'line',
        x: 145,
        y: 30,
        width: 3,
        height: 60,
        strokeWidth: 3,
        strokeColor: '#1a5490',
      },
      {
        id: generateId(),
        type: 'text',
        x: 160,
        y: 25,
        width: 385,
        height: 22,
        text: '{{commerceName}}',
        fontSize: 16,
        fontFamily: 'Arial',
        color: '#1a5490',
        align: 'left',
        bold: true,
      },
      {
        id: generateId(),
        type: 'text',
        x: 160,
        y: 48,
        width: 385,
        height: 18,
        text: 'Dr(a). {{doctorName}}',
        fontSize: 13,
        fontFamily: 'Arial',
        color: '#000000',
        align: 'left',
        bold: true,
      },
      {
        id: generateId(),
        type: 'text',
        x: 160,
        y: 67,
        width: 385,
        height: 15,
        text: '{{doctorSpecialty}} | CRM: {{doctorLicense}}',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#495057',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'text',
        x: 160,
        y: 84,
        width: 385,
        height: 13,
        text: '{{commerceAddress}} | {{commercePhone}}',
        fontSize: 9,
        fontFamily: 'Arial',
        color: '#6c757d',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'line',
        x: 50,
        y: 108,
        width: 495,
        height: 1,
        strokeWidth: 1,
        strokeColor: '#dee2e6',
      },
    ],
  },
  {
    id: 'header_exam_order_minimal',
    name: 'Pedido de Exame - Minimalista',
    description: 'Header limpo e objetivo',
    section: 'header',
    documentType: 'exam_order',
    pageSize: 'A4',
    orientation: 'portrait',
    icon: 'bi bi-clipboard2',
    elements: [
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 20,
        width: 495,
        height: 26,
        text: '{{commerceName}}',
        fontSize: 16,
        fontFamily: 'Arial',
        color: '#1a5490',
        align: 'left',
        bold: true,
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 48,
        width: 495,
        height: 20,
        text: 'SOLICITAÇÃO DE EXAMES COMPLEMENTARES',
        fontSize: 14,
        fontFamily: 'Arial',
        color: '#000000',
        align: 'left',
        bold: true,
      },
      {
        id: generateId(),
        type: 'line',
        x: 50,
        y: 73,
        width: 495,
        height: 2,
        strokeWidth: 2,
        strokeColor: '#1a5490',
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 82,
        width: 245,
        height: 16,
        text: 'Dr(a). {{doctorName}}',
        fontSize: 11,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'left',
        bold: true,
      },
      {
        id: generateId(),
        type: 'text',
        x: 300,
        y: 82,
        width: 245,
        height: 16,
        text: 'CRM: {{doctorLicense}}',
        fontSize: 11,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'right',
        bold: true,
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 100,
        width: 495,
        height: 14,
        text: '{{commerceAddress}} | Tel: {{commercePhone}}',
        fontSize: 9,
        fontFamily: 'Arial',
        color: '#6c757d',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'line',
        x: 50,
        y: 120,
        width: 495,
        height: 1,
        strokeWidth: 1,
        strokeColor: '#dee2e6',
      },
    ],
  },
  {
    id: 'header_reference_detailed',
    name: 'Encaminhamento - Detalhado',
    description: 'Header com informação completa',
    section: 'header',
    documentType: 'reference',
    pageSize: 'A4',
    orientation: 'portrait',
    icon: 'bi bi-arrow-right-square-fill',
    elements: [
      {
        id: generateId(),
        type: 'logo',
        x: 50,
        y: 20,
        width: 65,
        height: 65,
        src: '{{commerceLogo}}',
      },
      {
        id: generateId(),
        type: 'text',
        x: 130,
        y: 22,
        width: 415,
        height: 20,
        text: '{{commerceName}}',
        fontSize: 14,
        fontFamily: 'Arial',
        color: '#000000',
        align: 'left',
        bold: true,
      },
      {
        id: generateId(),
        type: 'text',
        x: 130,
        y: 42,
        width: 415,
        height: 16,
        text: '{{commerceAddress}}',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#495057',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'text',
        x: 130,
        y: 58,
        width: 415,
        height: 16,
        text: 'Tel: {{commercePhone}} | Email: {{commerceEmail}}',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#495057',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'text',
        x: 130,
        y: 74,
        width: 415,
        height: 16,
        text: 'CNPJ: {{commerceCnpj}}',
        fontSize: 9,
        fontFamily: 'Arial',
        color: '#6c757d',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'line',
        x: 50,
        y: 95,
        width: 495,
        height: 2,
        strokeWidth: 2,
        strokeColor: '#1a5490',
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 105,
        width: 495,
        height: 22,
        text: 'GUIA DE REFERÊNCIA E CONTRARREFERÊNCIA',
        fontSize: 13,
        fontFamily: 'Arial',
        color: '#1a5490',
        align: 'center',
        bold: true,
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 128,
        width: 245,
        height: 16,
        text: 'Médico Solicitante: Dr(a). {{doctorName}}',
        fontSize: 9,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'text',
        x: 300,
        y: 128,
        width: 245,
        height: 16,
        text: 'CRM: {{doctorLicense}}',
        fontSize: 9,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'right',
      },
    ],
  },

  // ========== FOOTERS ADICIONALES VARIANTES ==========
  {
    id: 'footer_prescription_qrcode_enhanced',
    name: 'Receita - QR Code Destacado',
    description: 'Footer com QR code e validação em destaque',
    section: 'footer',
    documentType: 'prescription',
    pageSize: 'A4',
    orientation: 'portrait',
    icon: 'bi bi-qr-code-scan',
    elements: [
      {
        id: generateId(),
        type: 'line',
        x: 50,
        y: 710,
        width: 495,
        height: 2,
        strokeWidth: 2,
        strokeColor: '#1a5490',
      },
      {
        id: generateId(),
        type: 'qrcode',
        x: 65,
        y: 725,
        width: 85,
        height: 85,
        data: '{{verificationUrl}}',
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 815,
        width: 115,
        height: 10,
        text: 'Verificar autenticidade',
        fontSize: 8,
        fontFamily: 'Arial',
        color: '#1a5490',
        align: 'center',
        bold: true,
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 827,
        width: 115,
        height: 9,
        text: '{{documentId}}',
        fontSize: 7,
        fontFamily: 'Arial',
        color: '#6c757d',
        align: 'center',
      },
      {
        id: generateId(),
        type: 'text',
        x: 180,
        y: 730,
        width: 180,
        height: 16,
        text: 'Data: {{prescriptionDate}}',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'text',
        x: 180,
        y: 748,
        width: 180,
        height: 14,
        text: 'Validade: 30 dias',
        fontSize: 9,
        fontFamily: 'Arial',
        color: '#dc3545',
        align: 'left',
        bold: true,
      },
      {
        id: generateId(),
        type: 'signature',
        x: 390,
        y: 735,
        width: 140,
        height: 50,
        src: '{{doctorSignature}}',
      },
      {
        id: generateId(),
        type: 'line',
        x: 380,
        y: 790,
        width: 160,
        height: 1,
        strokeWidth: 1,
        strokeColor: '#000000',
      },
      {
        id: generateId(),
        type: 'text',
        x: 370,
        y: 795,
        width: 180,
        height: 14,
        text: 'Dr(a). {{doctorName}}',
        fontSize: 11,
        fontFamily: 'Brush Script MT',
        color: '#000000',
        align: 'center',
      },
      {
        id: generateId(),
        type: 'text',
        x: 370,
        y: 811,
        width: 180,
        height: 12,
        text: 'CRM: {{doctorLicense}}',
        fontSize: 9,
        fontFamily: 'Arial',
        color: '#000000',
        align: 'center',
        bold: true,
      },
    ],
  },
  {
    id: 'footer_exam_order_simple',
    name: 'Exame - Simples',
    description: 'Footer objetivo para pedidos de exame',
    section: 'footer',
    documentType: 'exam_order',
    pageSize: 'A4',
    orientation: 'portrait',
    icon: 'bi bi-clipboard-check-fill',
    elements: [
      {
        id: generateId(),
        type: 'line',
        x: 50,
        y: 720,
        width: 495,
        height: 1,
        strokeWidth: 1,
        strokeColor: '#dee2e6',
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 730,
        width: 495,
        height: 14,
        text: 'IMPORTANTE: Apresentar documento de identidade e carteira do convênio',
        fontSize: 9,
        fontFamily: 'Arial',
        color: '#dc3545',
        align: 'center',
        bold: true,
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 755,
        width: 245,
        height: 14,
        text: 'Data: {{currentDate}}',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'text',
        x: 300,
        y: 755,
        width: 245,
        height: 14,
        text: 'Validade: 30 dias',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#495057',
        align: 'right',
      },
      {
        id: generateId(),
        type: 'signature',
        x: 70,
        y: 780,
        width: 130,
        height: 40,
        src: '{{doctorSignature}}',
      },
      {
        id: generateId(),
        type: 'line',
        x: 60,
        y: 823,
        width: 150,
        height: 1,
        strokeWidth: 1,
        strokeColor: '#000000',
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 828,
        width: 170,
        height: 12,
        text: 'Dr(a). {{doctorName}}',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#000000',
        align: 'center',
        bold: true,
      },
      {
        id: generateId(),
        type: 'text',
        x: 250,
        y: 810,
        width: 295,
        height: 12,
        text: 'CRM: {{doctorLicense}} | {{doctorSpecialty}}',
        fontSize: 9,
        fontFamily: 'Arial',
        color: '#495057',
        align: 'right',
      },
    ],
  },
  {
    id: 'footer_reference_detailed',
    name: 'Encaminhamento - Detalhado',
    description: 'Footer completo com contrarreferência',
    section: 'footer',
    documentType: 'reference',
    pageSize: 'A4',
    orientation: 'portrait',
    icon: 'bi bi-arrow-left-right',
    elements: [
      {
        id: generateId(),
        type: 'line',
        x: 50,
        y: 700,
        width: 495,
        height: 2,
        strokeWidth: 2,
        strokeColor: '#000000',
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 710,
        width: 495,
        height: 18,
        text: 'SOLICITAÇÃO DE CONTRARREFERÊNCIA',
        fontSize: 11,
        fontFamily: 'Arial',
        color: '#1a5490',
        align: 'left',
        bold: true,
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 730,
        width: 495,
        height: 14,
        text: 'Solicito ao colega que após avaliação e conduta, favor enviar relatório de contrarreferência para:',
        fontSize: 9,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 746,
        width: 495,
        height: 13,
        text: 'Dr(a). {{doctorName}} | CRM: {{doctorLicense}}',
        fontSize: 9,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'left',
        bold: true,
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 761,
        width: 495,
        height: 12,
        text: 'Tel: {{commercePhone}} | Email: {{commerceEmail}}',
        fontSize: 8,
        fontFamily: 'Arial',
        color: '#495057',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 785,
        width: 200,
        height: 13,
        text: 'Data: {{currentDate}}',
        fontSize: 9,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'signature',
        x: 70,
        y: 805,
        width: 130,
        height: 40,
        src: '{{doctorSignature}}',
      },
      {
        id: generateId(),
        type: 'line',
        x: 60,
        y: 848,
        width: 150,
        height: 1,
        strokeWidth: 1,
        strokeColor: '#000000',
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 853,
        width: 170,
        height: 11,
        text: 'Dr(a). {{doctorName}}',
        fontSize: 9,
        fontFamily: 'Monotype Corsiva',
        color: '#000000',
        align: 'center',
      },
      {
        id: generateId(),
        type: 'text',
        x: 320,
        y: 815,
        width: 225,
        height: 12,
        text: '{{doctorSpecialty}}',
        fontSize: 9,
        fontFamily: 'Arial',
        color: '#495057',
        align: 'right',
      },
      {
        id: generateId(),
        type: 'text',
        x: 320,
        y: 830,
        width: 225,
        height: 10,
        text: 'Protocolo: {{documentId}}',
        fontSize: 8,
        fontFamily: 'Arial',
        color: '#adb5bd',
        align: 'right',
      },
    ],
  },

  // ========== CONTENT ADICIONALES VARIANTES ==========
  {
    id: 'content_prescription_simple',
    name: 'Receita - Simplificada',
    description: 'Formato direto e objetivo',
    section: 'content',
    documentType: 'prescription',
    pageSize: 'A4',
    orientation: 'portrait',
    icon: 'bi bi-file-text',
    elements: [
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 140,
        width: 495,
        height: 24,
        text: 'PRESCRIÇÃO',
        fontSize: 16,
        fontFamily: 'Arial',
        color: '#1a5490',
        align: 'left',
        bold: true,
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 170,
        width: 495,
        height: 16,
        text: 'Paciente: {{patientName}} | CPF: {{patientId}} | Idade: {{patientAge}} anos',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 188,
        width: 495,
        height: 16,
        text: 'Data: {{prescriptionDate}}',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'line',
        x: 50,
        y: 210,
        width: 495,
        height: 1,
        strokeWidth: 1,
        strokeColor: '#000000',
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 225,
        width: 40,
        height: 25,
        text: 'Rp/',
        fontSize: 18,
        fontFamily: 'Times New Roman',
        color: '#000000',
        align: 'left',
        bold: true,
        italic: true,
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 255,
        width: 495,
        height: 420,
        text: '{{medications}}\n\nExemplo:\n\n1. Paracetamol 500mg\n   Tomar 1 comprimido VO a cada 6h se dor ou febre\n   Duração: 5 dias\n\n2. Omeprazol 20mg\n   Tomar 1 cápsula VO em jejum\n   Duração: 30 dias',
        fontSize: 11,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'left',
        lineHeight: 1.8,
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 685,
        width: 495,
        height: 30,
        text: '{{instructions}}',
        fontSize: 9,
        fontFamily: 'Arial',
        color: '#495057',
        align: 'left',
        lineHeight: 1.5,
      },
    ],
  },
  {
    id: 'content_prescription_example_pdf',
    name: 'Receita - Exemplo PDF',
    description: 'Template baseado no exemplo de PDF compartilhado com estrutura complexa',
    section: 'content',
    documentType: 'prescription',
    pageSize: 'A4',
    orientation: 'portrait',
    icon: 'bi bi-file-earmark-text',
    elements: [
      // Título principal con borde superior
      {
        id: generateId(),
        type: 'line',
        x: 40,
        y: 40,
        width: 515,
        height: 1,
        strokeWidth: 2,
        strokeColor: '#000000',
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 50,
        width: 495,
        height: 30,
        text: 'Prescrição de medicamento',
        fontSize: 18,
        fontFamily: 'Arial',
        color: '#000000',
        align: 'center',
        bold: true,
      },
      {
        id: generateId(),
        type: 'line',
        x: 40,
        y: 90,
        width: 515,
        height: 1,
        strokeWidth: 2,
        strokeColor: '#000000',
      },
      // Sección del médico con caja
      {
        id: generateId(),
        type: 'line',
        x: 40,
        y: 100,
        width: 1,
        height: 60,
        strokeWidth: 1,
        strokeColor: '#000000',
      },
      {
        id: generateId(),
        type: 'line',
        x: 555,
        y: 100,
        width: 1,
        height: 60,
        strokeWidth: 1,
        strokeColor: '#000000',
      },
      {
        id: generateId(),
        type: 'line',
        x: 40,
        y: 100,
        width: 515,
        height: 1,
        strokeWidth: 1,
        strokeColor: '#000000',
      },
      {
        id: generateId(),
        type: 'line',
        x: 40,
        y: 160,
        width: 515,
        height: 1,
        strokeWidth: 1,
        strokeColor: '#000000',
      },
      // Columna izquierda: Datos del médico
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 110,
        width: 200,
        height: 16,
        text: 'Médico: {{doctorName}}',
        fontSize: 12,
        fontFamily: 'Arial',
        color: '#000000',
        align: 'left',
        bold: true,
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 130,
        width: 200,
        height: 16,
        text: 'CRM: {{doctorCrm}}',
        fontSize: 12,
        fontFamily: 'Arial',
        color: '#000000',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 145,
        width: 200,
        height: 16,
        text: 'Especialidade: {{doctorSpecialty}}',
        fontSize: 12,
        fontFamily: 'Arial',
        color: '#000000',
        align: 'left',
      },
      // Columna derecha: Fecha y otros
      {
        id: generateId(),
        type: 'text',
        x: 300,
        y: 110,
        width: 245,
        height: 16,
        text: 'Endereço: {{doctorAddress}}',
        fontSize: 12,
        fontFamily: 'Arial',
        color: '#000000',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'text',
        x: 300,
        y: 130,
        width: 245,
        height: 16,
        text: 'Telefone: {{doctorPhone}}',
        fontSize: 12,
        fontFamily: 'Arial',
        color: '#000000',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'text',
        x: 300,
        y: 145,
        width: 245,
        height: 16,
        text: 'Data: {{prescriptionDate}}',
        fontSize: 12,
        fontFamily: 'Arial',
        color: '#000000',
        align: 'left',
      },
      // Sección del paciente con caja
      {
        id: generateId(),
        type: 'line',
        x: 40,
        y: 170,
        width: 1,
        height: 50,
        strokeWidth: 1,
        strokeColor: '#000000',
      },
      {
        id: generateId(),
        type: 'line',
        x: 555,
        y: 170,
        width: 1,
        height: 50,
        strokeWidth: 1,
        strokeColor: '#000000',
      },
      {
        id: generateId(),
        type: 'line',
        x: 40,
        y: 170,
        width: 515,
        height: 1,
        strokeWidth: 1,
        strokeColor: '#000000',
      },
      {
        id: generateId(),
        type: 'line',
        x: 40,
        y: 220,
        width: 515,
        height: 1,
        strokeWidth: 1,
        strokeColor: '#000000',
      },
      // Columna izquierda: Datos del paciente
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 180,
        width: 200,
        height: 16,
        text: 'Paciente: {{patientName}}',
        fontSize: 12,
        fontFamily: 'Arial',
        color: '#000000',
        align: 'left',
        bold: true,
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 200,
        width: 200,
        height: 16,
        text: 'Idade: {{patientAge}} anos',
        fontSize: 12,
        fontFamily: 'Arial',
        color: '#000000',
        align: 'left',
      },
      // Columna derecha: ID del paciente
      {
        id: generateId(),
        type: 'text',
        x: 300,
        y: 180,
        width: 245,
        height: 16,
        text: 'CPF/RG: {{patientId}}',
        fontSize: 12,
        fontFamily: 'Arial',
        color: '#000000',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'text',
        x: 300,
        y: 200,
        width: 245,
        height: 16,
        text: 'Endereço: {{patientAddress}}',
        fontSize: 12,
        fontFamily: 'Arial',
        color: '#000000',
        align: 'left',
      },
      // Sección de medicamentos con tabla simulada
      {
        id: generateId(),
        type: 'line',
        x: 40,
        y: 230,
        width: 1,
        height: 250,
        strokeWidth: 1,
        strokeColor: '#000000',
      },
      {
        id: generateId(),
        type: 'line',
        x: 555,
        y: 230,
        width: 1,
        height: 250,
        strokeWidth: 1,
        strokeColor: '#000000',
      },
      {
        id: generateId(),
        type: 'line',
        x: 40,
        y: 230,
        width: 515,
        height: 1,
        strokeWidth: 1,
        strokeColor: '#000000',
      },
      {
        id: generateId(),
        type: 'line',
        x: 40,
        y: 480,
        width: 515,
        height: 1,
        strokeWidth: 1,
        strokeColor: '#000000',
      },
      // Rp/ - Abreviação latina
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 240,
        width: 50,
        height: 25,
        text: 'Rp/',
        fontSize: 20,
        fontFamily: 'Times New Roman',
        color: '#000000',
        align: 'left',
        bold: true,
        italic: true,
      },
      // Medicamentos en formato de lista con líneas separadoras
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 270,
        width: 495,
        height: 200,
        text: '{{medications}}\n\nExemplo:\n\n1. Medicamento 1 - Dosagem: 500mg\n   Via: Oral - Frequência: 3x/dia\n   Duração: 7 dias\n\n2. Medicamento 2 - Dosagem: 20mg\n   Via: Oral - Frequência: 1x/dia\n   Duração: 30 dias',
        fontSize: 11,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'left',
        lineHeight: 1.8,
      },
      // Sección de orientações con caja
      {
        id: generateId(),
        type: 'line',
        x: 40,
        y: 490,
        width: 1,
        height: 80,
        strokeWidth: 1,
        strokeColor: '#000000',
      },
      {
        id: generateId(),
        type: 'line',
        x: 555,
        y: 490,
        width: 1,
        height: 80,
        strokeWidth: 1,
        strokeColor: '#000000',
      },
      {
        id: generateId(),
        type: 'line',
        x: 40,
        y: 490,
        width: 515,
        height: 1,
        strokeWidth: 1,
        strokeColor: '#000000',
      },
      {
        id: generateId(),
        type: 'line',
        x: 40,
        y: 570,
        width: 515,
        height: 1,
        strokeWidth: 1,
        strokeColor: '#000000',
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 500,
        width: 495,
        height: 16,
        text: 'Orientações Adicionais:',
        fontSize: 12,
        fontFamily: 'Arial',
        color: '#000000',
        align: 'left',
        bold: true,
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 520,
        width: 495,
        height: 40,
        text: '{{instructions}}',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#495057',
        align: 'left',
        lineHeight: 1.5,
      },
      // Sección de firma con caja
      {
        id: generateId(),
        type: 'line',
        x: 40,
        y: 580,
        width: 1,
        height: 60,
        strokeWidth: 1,
        strokeColor: '#000000',
      },
      {
        id: generateId(),
        type: 'line',
        x: 555,
        y: 580,
        width: 1,
        height: 60,
        strokeWidth: 1,
        strokeColor: '#000000',
      },
      {
        id: generateId(),
        type: 'line',
        x: 40,
        y: 580,
        width: 515,
        height: 1,
        strokeWidth: 1,
        strokeColor: '#000000',
      },
      {
        id: generateId(),
        type: 'line',
        x: 40,
        y: 640,
        width: 515,
        height: 1,
        strokeWidth: 1,
        strokeColor: '#000000',
      },
      {
        id: generateId(),
        type: 'text',
        x: 300,
        y: 590,
        width: 245,
        height: 16,
        text: 'Assinatura do Médico',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#000000',
        align: 'center',
      },
      {
        id: generateId(),
        type: 'line',
        x: 300,
        y: 610,
        width: 245,
        height: 1,
        strokeWidth: 1,
        strokeColor: '#000000',
      },
      // Imagen opcional (sello o logo)
      {
        id: generateId(),
        type: 'image',
        x: 450,
        y: 590,
        width: 80,
        height: 40,
        src: '{{doctorStamp}}', // Placeholder para sello
      },
    ],
  },
  {
    id: 'content_exam_order_detailed',
    name: 'Exame - Detalhado',
    description: 'Solicitação completa com justificativa',
    section: 'content',
    documentType: 'exam_order',
    pageSize: 'A4',
    orientation: 'portrait',
    icon: 'bi bi-clipboard2-pulse-fill',
    elements: [
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 145,
        width: 495,
        height: 20,
        text: 'IDENTIFICAÇÃO DO PACIENTE',
        fontSize: 11,
        fontFamily: 'Arial',
        color: '#1a5490',
        align: 'left',
        bold: true,
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 168,
        width: 330,
        height: 16,
        text: 'Nome: {{patientName}}',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'text',
        x: 385,
        y: 168,
        width: 160,
        height: 16,
        text: 'Data: {{currentDate}}',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'right',
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 186,
        width: 165,
        height: 16,
        text: 'CPF: {{patientId}}',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'text',
        x: 220,
        y: 186,
        width: 160,
        height: 16,
        text: 'Idade: {{patientAge}}',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'text',
        x: 385,
        y: 186,
        width: 160,
        height: 16,
        text: 'Sexo: {{patientGender}}',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'right',
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 204,
        width: 495,
        height: 16,
        text: 'Convênio: {{patientInsurance}}',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'line',
        x: 50,
        y: 226,
        width: 495,
        height: 1,
        strokeWidth: 1,
        strokeColor: '#dee2e6',
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 238,
        width: 495,
        height: 18,
        text: 'HIPÓTESE DIAGNÓSTICA (CID-10)',
        fontSize: 11,
        fontFamily: 'Arial',
        color: '#1a5490',
        align: 'left',
        bold: true,
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 259,
        width: 495,
        height: 50,
        text: '{{diagnosis}}',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'left',
        lineHeight: 1.6,
      },
      {
        id: generateId(),
        type: 'line',
        x: 50,
        y: 314,
        width: 495,
        height: 1,
        strokeWidth: 1,
        strokeColor: '#dee2e6',
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 326,
        width: 495,
        height: 18,
        text: 'JUSTIFICATIVA CLÍNICA',
        fontSize: 11,
        fontFamily: 'Arial',
        color: '#1a5490',
        align: 'left',
        bold: true,
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 347,
        width: 495,
        height: 60,
        text: '{{clinicalJustification}}',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'left',
        lineHeight: 1.6,
      },
      {
        id: generateId(),
        type: 'line',
        x: 50,
        y: 412,
        width: 495,
        height: 1,
        strokeWidth: 1,
        strokeColor: '#dee2e6',
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 424,
        width: 495,
        height: 18,
        text: 'EXAMES SOLICITADOS',
        fontSize: 11,
        fontFamily: 'Arial',
        color: '#1a5490',
        align: 'left',
        bold: true,
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 445,
        width: 495,
        height: 180,
        text: '{{examsList}}\n\nExemplo:\n☐ Hemograma completo\n☐ PCR (Proteína C Reativa)\n☐ VHS (Velocidade de Hemosedimentação)\n☐ Função hepática (TGO, TGP, FA, Bilirrubinas)\n☐ Função renal (Ureia, Creatinina, Clearance)',
        fontSize: 11,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'left',
        lineHeight: 2.0,
      },
      {
        id: generateId(),
        type: 'line',
        x: 50,
        y: 630,
        width: 495,
        height: 1,
        strokeWidth: 1,
        strokeColor: '#dee2e6',
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 642,
        width: 495,
        height: 16,
        text: 'PREPARO E INSTRUÇÕES',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#dc3545',
        align: 'left',
        bold: true,
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 662,
        width: 495,
        height: 50,
        text: '{{preparationInstructions}}\n\nExemplo:\n• Jejum de 8-12 horas\n• Trazer resultados anteriores',
        fontSize: 9,
        fontFamily: 'Arial',
        color: '#495057',
        align: 'left',
        lineHeight: 1.6,
      },
    ],
  },
  {
    id: 'content_reference_simple',
    name: 'Encaminhamento - Simples',
    description: 'Referência objetiva e direta',
    section: 'content',
    documentType: 'reference',
    pageSize: 'A4',
    orientation: 'portrait',
    icon: 'bi bi-arrow-right',
    elements: [
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 145,
        width: 495,
        height: 20,
        text: 'DADOS DO PACIENTE',
        fontSize: 11,
        fontFamily: 'Arial',
        color: '#1a5490',
        align: 'left',
        bold: true,
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 170,
        width: 495,
        height: 16,
        text: 'Nome: {{patientName}} | CPF: {{patientId}}',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 188,
        width: 245,
        height: 16,
        text: 'Idade: {{patientAge}}',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'text',
        x: 300,
        y: 188,
        width: 245,
        height: 16,
        text: 'Sexo: {{patientGender}}',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'right',
      },
      {
        id: generateId(),
        type: 'line',
        x: 50,
        y: 210,
        width: 495,
        height: 1,
        strokeWidth: 1,
        strokeColor: '#000000',
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 222,
        width: 495,
        height: 18,
        text: 'ENCAMINHAR PARA:',
        fontSize: 11,
        fontFamily: 'Arial',
        color: '#1a5490',
        align: 'left',
        bold: true,
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 243,
        width: 495,
        height: 16,
        text: 'Especialidade: {{specialty}}',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'left',
        bold: true,
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 261,
        width: 495,
        height: 16,
        text: 'Especialista: {{specialistName}}',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'line',
        x: 50,
        y: 283,
        width: 495,
        height: 1,
        strokeWidth: 1,
        strokeColor: '#dee2e6',
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 295,
        width: 495,
        height: 18,
        text: 'MOTIVO DO ENCAMINHAMENTO',
        fontSize: 11,
        fontFamily: 'Arial',
        color: '#1a5490',
        align: 'left',
        bold: true,
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 316,
        width: 495,
        height: 140,
        text: '{{referenceReason}}',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'left',
        lineHeight: 1.6,
      },
      {
        id: generateId(),
        type: 'line',
        x: 50,
        y: 461,
        width: 495,
        height: 1,
        strokeWidth: 1,
        strokeColor: '#dee2e6',
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 473,
        width: 495,
        height: 18,
        text: 'RESUMO CLÍNICO',
        fontSize: 11,
        fontFamily: 'Arial',
        color: '#1a5490',
        align: 'left',
        bold: true,
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 494,
        width: 495,
        height: 180,
        text: '{{clinicalSummary}}',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'left',
        lineHeight: 1.6,
      },
    ],
  },

  // ========== CONTENT PARA GUIA DE ENCAMINHAMENTO/REFERÊNCIA (CFM) ==========
  {
    id: 'content_reference_cfm',
    name: 'Encaminhamento - CFM',
    description: 'Guia de referência conforme CFM',
    section: 'content',
    documentType: 'reference',
    pageSize: 'A4',
    orientation: 'portrait',
    icon: 'bi bi-arrow-right-circle',
    elements: [
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 155,
        width: 495,
        height: 22,
        text: 'DADOS DO PACIENTE',
        fontSize: 12,
        fontFamily: 'Arial',
        color: '#1a5490',
        align: 'left',
        bold: true,
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 182,
        width: 495,
        height: 16,
        text: 'Nome completo: {{patientName}}',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 200,
        width: 245,
        height: 16,
        text: 'CPF/RG: {{patientId}}',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'text',
        x: 300,
        y: 200,
        width: 120,
        height: 16,
        text: 'Idade: {{patientAge}}',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'text',
        x: 425,
        y: 200,
        width: 120,
        height: 16,
        text: 'Sexo: {{patientGender}}',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 218,
        width: 495,
        height: 16,
        text: 'Telefone: {{patientPhone}}',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'line',
        x: 50,
        y: 240,
        width: 495,
        height: 2,
        strokeWidth: 2,
        strokeColor: '#dee2e6',
      },
      // ENCAMINHAMENTO (Obrigatório)
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 252,
        width: 495,
        height: 20,
        text: 'ENCAMINHAR PARA:',
        fontSize: 11,
        fontFamily: 'Arial',
        color: '#1a5490',
        align: 'left',
        bold: true,
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 275,
        width: 495,
        height: 18,
        text: 'Especialista: {{specialistName}}',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 293,
        width: 495,
        height: 18,
        text: 'Especialidade: {{specialty}}',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'line',
        x: 50,
        y: 318,
        width: 495,
        height: 1,
        strokeWidth: 1,
        strokeColor: '#dee2e6',
      },
      // MOTIVO DO ENCAMINHAMENTO (Obrigatório CFM)
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 330,
        width: 495,
        height: 20,
        text: 'MOTIVO DO ENCAMINHAMENTO',
        fontSize: 11,
        fontFamily: 'Arial',
        color: '#1a5490',
        align: 'left',
        bold: true,
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 353,
        width: 495,
        height: 90,
        text: '{{referenceReason}}',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'left',
        lineHeight: 1.6,
      },
      {
        id: generateId(),
        type: 'line',
        x: 50,
        y: 448,
        width: 495,
        height: 1,
        strokeWidth: 1,
        strokeColor: '#dee2e6',
      },
      // RESUMO CLÍNICO (Obrigatório CFM)
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 460,
        width: 495,
        height: 20,
        text: 'RESUMO CLÍNICO / HISTÓRIA',
        fontSize: 11,
        fontFamily: 'Arial',
        color: '#1a5490',
        align: 'left',
        bold: true,
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 483,
        width: 495,
        height: 110,
        text: '{{clinicalSummary}}',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'left',
        lineHeight: 1.6,
      },
      {
        id: generateId(),
        type: 'line',
        x: 50,
        y: 598,
        width: 495,
        height: 1,
        strokeWidth: 1,
        strokeColor: '#dee2e6',
      },
      // EXAMES E TRATAMENTOS REALIZADOS
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 610,
        width: 495,
        height: 18,
        text: 'EXAMES/TRATAMENTOS JÁ REALIZADOS',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#1a5490',
        align: 'left',
        bold: true,
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 631,
        width: 495,
        height: 70,
        text: '{{previousTreatments}}',
        fontSize: 9,
        fontFamily: 'Arial',
        color: '#495057',
        align: 'left',
        lineHeight: 1.5,
      },
    ],
  },
  // ========== NOVO TEMPLATE COMPLETO ==========
  // Header moderno para receitas
  {
    id: 'header_prescription_modern_complete',
    name: 'Receita - Moderna Completa',
    description: 'Header moderno com design completo',
    section: 'header',
    documentType: 'prescription',
    pageSize: 'A4',
    orientation: 'portrait',
    icon: 'bi bi-capsule-pill',
    elements: [
      {
        id: generateId(),
        type: 'rectangle',
        x: 40,
        y: 15,
        width: 515,
        height: 100,
        fillColor: '#f8f9fa',
        strokeColor: '#dee2e6',
        strokeWidth: 2,
        strokeStyle: 'solid',
      },
      {
        id: generateId(),
        type: 'logo',
        x: 50,
        y: 25,
        width: 60,
        height: 60,
        src: '{{commerceLogo}}',
      },
      {
        id: generateId(),
        type: 'text',
        x: 120,
        y: 25,
        width: 400,
        height: 20,
        text: '{{commerceName}}',
        fontSize: 16,
        fontFamily: 'Arial',
        color: '#1a5490',
        align: 'left',
        bold: true,
      },
      {
        id: generateId(),
        type: 'text',
        x: 120,
        y: 50,
        width: 400,
        height: 16,
        text: 'Dr(a). {{doctorName}} - CRM: {{doctorLicense}}',
        fontSize: 12,
        fontFamily: 'Arial',
        color: '#495057',
        align: 'left',
        bold: true,
      },
      {
        id: generateId(),
        type: 'text',
        x: 120,
        y: 70,
        width: 400,
        height: 14,
        text: '{{doctorSpecialty}} | Tel: {{commercePhone}} | {{commerceAddress}}',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#6c757d',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'line',
        x: 40,
        y: 120,
        width: 515,
        height: 3,
        strokeWidth: 3,
        strokeColor: '#1a5490',
      },
    ],
  },
  // Content completo para receitas
  {
    id: 'content_prescription_modern_complete',
    name: 'Receita - Moderna Completa',
    description: 'Conteúdo completo com paciente, medicamentos e indicações',
    section: 'content',
    documentType: 'prescription',
    pageSize: 'A4',
    orientation: 'portrait',
    icon: 'bi bi-capsule-pill',
    elements: [
      // Título
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 140,
        width: 495,
        height: 30,
        text: 'RECEITA MÉDICA',
        fontSize: 20,
        fontFamily: 'Arial',
        color: '#1a5490',
        align: 'center',
        bold: true,
      },
      {
        id: generateId(),
        type: 'line',
        x: 50,
        y: 175,
        width: 495,
        height: 2,
        strokeWidth: 2,
        strokeColor: '#1a5490',
      },
      // Datos del paciente
      {
        id: generateId(),
        type: 'rectangle',
        x: 50,
        y: 190,
        width: 495,
        height: 80,
        fillColor: '#f8f9fa',
        strokeColor: '#dee2e6',
        strokeWidth: 2,
        strokeStyle: 'solid',
      },
      {
        id: generateId(),
        type: 'text',
        x: 60,
        y: 195,
        width: 475,
        height: 18,
        text: 'PACIENTE',
        fontSize: 12,
        fontFamily: 'Arial',
        color: '#1a5490',
        align: 'left',
        bold: true,
      },
      {
        id: generateId(),
        type: 'text',
        x: 60,
        y: 215,
        width: 230,
        height: 16,
        text: 'Nome: {{patientName}}',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'text',
        x: 300,
        y: 215,
        width: 230,
        height: 16,
        text: 'Idade: {{patientAge}} anos',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'text',
        x: 60,
        y: 235,
        width: 230,
        height: 16,
        text: 'CPF/RG: {{patientId}}',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'text',
        x: 300,
        y: 235,
        width: 230,
        height: 16,
        text: 'Data: {{prescriptionDate}}',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'text',
        x: 60,
        y: 255,
        width: 470,
        height: 14,
        text: 'Endereço: {{patientAddress}}',
        fontSize: 9,
        fontFamily: 'Arial',
        color: '#495057',
        align: 'left',
      },
      // Medicamentos
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 285,
        width: 495,
        height: 20,
        text: 'PRESCRIÇÃO',
        fontSize: 14,
        fontFamily: 'Arial',
        color: '#1a5490',
        align: 'left',
        bold: true,
      },
      {
        id: generateId(),
        type: 'rectangle',
        x: 50,
        y: 310,
        width: 495,
        height: 200,
        fillColor: '#ffffff',
        strokeColor: '#dee2e6',
        strokeWidth: 2,
        strokeStyle: 'solid',
      },
      {
        id: generateId(),
        type: 'text',
        x: 60,
        y: 320,
        width: 475,
        height: 180,
        text: '{{medications}}\n\nExemplo de prescrição:\n\nRp/\n\n1. Medicamento A - 500mg\n   Via oral, 1 comprimido a cada 8 horas\n   Duração: 7 dias\n\n2. Medicamento B - 10mg\n   Via oral, 1 comprimido ao dia\n   Duração: 30 dias\n\n3. Medicamento C - 20mg\n   Aplicar topicamente 2x ao dia\n   Duração: 14 dias',
        fontSize: 11,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'left',
        lineHeight: 1.6,
      },
      // Indicaciones
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 525,
        width: 495,
        height: 20,
        text: 'INDICAÇÕES E ORIENTAÇÕES',
        fontSize: 14,
        fontFamily: 'Arial',
        color: '#1a5490',
        align: 'left',
        bold: true,
      },
      {
        id: generateId(),
        type: 'rectangle',
        x: 50,
        y: 550,
        width: 495,
        height: 100,
        fillColor: '#f8f9fa',
        strokeColor: '#dee2e6',
        strokeWidth: 2,
        strokeStyle: 'solid',
      },
      {
        id: generateId(),
        type: 'text',
        x: 60,
        y: 560,
        width: 475,
        height: 80,
        text: '{{instructions}}\n\n• Tomar com água\n• Não exceder a dose recomendada\n• Em caso de reação alérgica, suspender e procurar atendimento médico\n• Retornar para consulta de acompanhamento',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#495057',
        align: 'left',
        lineHeight: 1.5,
      },
    ],
  },
  // Footer moderno para receitas
  {
    id: 'footer_prescription_modern_complete',
    name: 'Receita - Moderna Completa',
    description: 'Footer com assinatura e dados do médico',
    section: 'footer',
    documentType: 'prescription',
    pageSize: 'A4',
    orientation: 'portrait',
    icon: 'bi bi-capsule-pill',
    elements: [
      {
        id: generateId(),
        type: 'line',
        x: 50,
        y: 750,
        width: 495,
        height: 2,
        strokeWidth: 2,
        strokeColor: '#1a5490',
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 765,
        width: 200,
        height: 16,
        text: 'Data: {{prescriptionDate}}',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'left',
      },
      {
        id: generateId(),
        type: 'text',
        x: 300,
        y: 765,
        width: 245,
        height: 16,
        text: 'Assinatura do Médico:',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#212529',
        align: 'left',
        bold: true,
      },
      {
        id: generateId(),
        type: 'line',
        x: 300,
        y: 785,
        width: 245,
        height: 1,
        strokeWidth: 1,
        strokeColor: '#000000',
      },
      {
        id: generateId(),
        type: 'text',
        x: 300,
        y: 790,
        width: 245,
        height: 14,
        text: 'Dr(a). {{doctorName}}',
        fontSize: 10,
        fontFamily: 'Arial',
        color: '#495057',
        align: 'center',
      },
      {
        id: generateId(),
        type: 'text',
        x: 300,
        y: 805,
        width: 245,
        height: 14,
        text: 'CRM: {{doctorLicense}}',
        fontSize: 9,
        fontFamily: 'Arial',
        color: '#495057',
        align: 'center',
      },
      {
        id: generateId(),
        type: 'text',
        x: 50,
        y: 780,
        width: 200,
        height: 40,
        text: 'Este documento é válido apenas com assinatura do profissional responsável.',
        fontSize: 8,
        fontFamily: 'Arial',
        color: '#6c757d',
        align: 'left',
        lineHeight: 1.3,
      },
    ],
  },
];
